// ============================================================
// MODERN STYLES - WITH SCROLLING FIX & REDUCED WHITESPACE
// ============================================================
const stylesModern = {
  appContainer: {
    minHeight: '100vh',
    background: COLORS.background,
    display: 'flex',
    overflow: 'hidden',
  },
  mainContent: {
    flex: 1,
    padding: '8px 20px 20px 20px',
    marginLeft: '250px',
    transition: 'margin-left 0.3s ease',
    minHeight: '100vh',
    maxHeight: '100vh',
    width: 'calc(100% - 250px)',
    maxWidth: 'calc(100% - 250px)',
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  loadingContainer: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    background: COLORS.background,
    gap: '16px',
  },
  spinner: {
    width: '40px',
    height: '40px',
    border: `4px solid ${COLORS.border}`,
    borderTop: `4px solid ${COLORS.primary}`,
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  errorContainer: {
    maxWidth: '500px',
    margin: '40px auto',
    textAlign: 'center',
    padding: '40px',
    background: COLORS.cardBg,
    borderRadius: '12px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
  },
  errorIcon: { fontSize: '48px', marginBottom: '16px' },
  primaryButton: {
    padding: '10px 24px',
    background: COLORS.primary,
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    marginTop: '16px',
    fontSize: '14px',
    fontWeight: 600,
  },
  topBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '4px 0',
    marginBottom: '8px',
    flexWrap: 'wrap',
    gap: '8px',
  },
  topBarLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  menuButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: COLORS.text,
    padding: '4px',
    display: 'flex',
    alignItems: 'center',
  },
  searchWrapper: {
    display: 'flex',
    alignItems: 'center',
    background: 'white',
    borderRadius: '8px',
    padding: '4px 12px',
    border: `1px solid ${COLORS.border}`,
    width: '240px',
  },
  searchIcon: {
    color: COLORS.muted,
    marginRight: '8px',
    display: 'flex',
    alignItems: 'center',
  },
  searchInput: {
    border: 'none',
    outline: 'none',
    padding: '6px 0',
    fontSize: '13px',
    width: '100%',
    background: 'transparent',
  },
  topBarRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  refreshBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '18px',
    color: COLORS.muted,
    padding: '4px 8px',
    '&:hover': { color: COLORS.primary },
  },
  userBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'white',
    padding: '4px 12px 4px 4px',
    borderRadius: '20px',
    border: `1px solid ${COLORS.border}`,
  },
  userAvatar: {
    width: '28px',
    height: '28px',
    background: COLORS.primary,
    color: 'white',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: 600,
  },
  userName: {
    fontSize: '12px',
    fontWeight: 500,
    color: COLORS.text,
  },
  welcomeSection: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '10px',
    flexWrap: 'wrap',
    gap: '8px',
  },
  welcomeTitle: {
    fontSize: '20px',
    fontWeight: 700,
    color: COLORS.primary,
    margin: 0,
  },
  welcomeSubtitle: {
    fontSize: '13px',
    color: COLORS.muted,
    margin: '2px 0 0 0',
  },
  lastUpdated: {
    color: COLORS.muted,
    fontSize: '11px',
    marginLeft: '8px',
  },
  filterBadges: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
  },
  filterBadge: {
    padding: '3px 10px',
    background: 'white',
    borderRadius: '10px',
    border: `1px solid ${COLORS.border}`,
    fontSize: '11px',
    color: COLORS.text,
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '10px',
    marginBottom: '12px',
  },
  kpiCard: {
    background: 'white',
    padding: '12px 16px',
    borderRadius: '12px',
    border: `1px solid ${COLORS.border}`,
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  kpiIconWrapper: {
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kpiIcon: {
    fontSize: '18px',
  },
  kpiLabel: {
    fontSize: '10px',
    color: COLORS.muted,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  kpiValue: {
    fontSize: '18px',
    fontWeight: 700,
    color: COLORS.primary,
    lineHeight: 1.2,
  },
  kpiSub: {
    fontSize: '10px',
    color: COLORS.muted,
    marginTop: '2px',
  },
  filtersRowModern: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    marginBottom: '12px',
    background: 'white',
    padding: '10px 14px',
    borderRadius: '12px',
    border: `1px solid ${COLORS.border}`,
    alignItems: 'flex-end',
  },
  filterGroupModern: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: '140px',
    flex: 1,
    maxWidth: '200px',
  },
  smallButtonModern: {
    padding: '2px 8px',
    fontSize: '10px',
    background: COLORS.border,
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    color: COLORS.textMuted,
    fontWeight: 600,
  },
  scoreFilterGroupModern: {
    display: 'flex',
    gap: '6px',
    alignItems: 'center',
  },
  filterInputSmallModern: {
    padding: '5px 6px',
    borderRadius: '6px',
    border: `1px solid ${COLORS.border}`,
    fontSize: '11px',
    background: 'white',
    width: '45px',
    textAlign: 'center',
  },
  resetButtonModern: {
    padding: '5px 14px',
    background: COLORS.border,
    border: 'none',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    color: COLORS.text,
    height: '30px',
    alignSelf: 'flex-end',
  },
  chartsRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
    marginBottom: '16px',
  },
  chartCard: {
    background: 'white',
    padding: '14px 18px',
    borderRadius: '12px',
    border: `1px solid ${COLORS.border}`,
  },
  chartCardTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: COLORS.primary,
    margin: '0 0 10px 0',
  },
  doughnutContainer: {
    height: '180px',
    position: 'relative',
  },
  barContainer: {
    height: '180px',
  },
  targetRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))',
    gap: '12px',
    marginBottom: '16px',
  },
  targetCard: {
    background: 'white',
    padding: '12px 16px',
    borderRadius: '12px',
    border: `1px solid ${COLORS.border}`,
  },
  targetHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '6px',
  },
  targetLabel: {
    fontSize: '12px',
    color: COLORS.muted,
  },
  targetValue: {
    fontSize: '16px',
    fontWeight: 700,
    color: COLORS.primary,
  },
  targetProgress: {
    height: '5px',
    background: COLORS.border,
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '6px',
  },
  targetProgressBar: {
    height: '100%',
    borderRadius: '4px',
    transition: 'width 0.5s ease',
  },
  targetMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11px',
    color: COLORS.muted,
  },
  recentGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
    marginBottom: '16px',
  },
  recentCard: {
    background: 'white',
    padding: '14px 18px',
    borderRadius: '12px',
    border: `1px solid ${COLORS.border}`,
  },
  recentTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: COLORS.primary,
    margin: '0 0 10px 0',
  },
  recentList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  recentItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '6px 0',
    borderBottom: `1px solid ${COLORS.border}`,
    '&:last-child': { borderBottom: 'none' },
  },
  recentName: {
    fontSize: '12px',
    fontWeight: 600,
    color: COLORS.text,
  },
  recentMeta: {
    fontSize: '11px',
    color: COLORS.muted,
  },
  recentTime: {
    fontSize: '11px',
    color: COLORS.muted,
    flexShrink: 0,
    marginLeft: '10px',
  },
  emptyState: {
    textAlign: 'center',
    padding: '16px',
    color: COLORS.muted,
    fontSize: '12px',
  },
};

// Add spin animation
if (typeof document !== 'undefined') {
  const style = document.createElement('style');
  style.textContent = `
    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
  `;
  document.head.appendChild(style);
}
